Maddev
makcwell/React-PostList pull request #18
Opened 2023-03-26 23:14 UTC by aleksei-zhuikov

__Что сделал:__
+ страницу информацию о посте ```<CardInfo />``` со статическим ID
   - для просмотра нужно снять комментарий с нее в ```app.js```
+ Запрос, получение и динамическое отображение данных о посте с сервера
   - фото поста, время добавления, автор, название и описание, отображение комментариев
+ Форму добавления комментария нужно доработать
+ Были установлены новые зависимости

2023-03-27 15:58 UTC, makcwell commented on src/API/PostsApi.js
> +    }
В нашем случае это абсолютно ненужный запрос. Мы уже получаем массив объектов из которого просто нужно достать нужный объект

2023-03-27 20:12 UTC, aleksei-zhuikov commented on src/API/PostsApi.js
> +    }
Это через props доставать? Тогда может контекст для поста сделать?

2023-03-28 16:20 UTC, aleksei-zhuikov commented on src/API/PostsApi.js
> +    }
Сделал через props

2023-03-28 20:53 UTC, makcwell requested changes

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/Card/myCard.jsx
>  import Chip from '@mui/material/Chip';
Убрать лишний импорт
 import { CardMedia, Typography, CardContent , Chip } from '@mui/material'

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/Card/myCard.jsx
> +    console.log('props приходит в MyCard >>', card)
Логи нужно убирать после использования

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/Card/myCard.jsx
>      }
Этот хэндлер лишний, пока не добавлена возможность сортировки по тегам.

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/Card/myCard.jsx
> +                                </svg>
Зачем вставлять весь svg код? В MUI есть отличные иконки.
Иконка для сообщений - import ChatIcon from '@mui/icons-material/Chat';
Лайк - import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';

Для отображения количества комментов или лайков на этих иконках можно использовать - import Badge from '@mui/material/Badge';

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +import { useNavigate } from "react-router-dom";
import { Avatar, Button, CardContent, CardHeader, CardMedia, Chip, Box, Paper, Grid  } from '@mui/material';
import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect} from 'react'

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +                                            <path clip-rule="evenodd" d="M12 19.343c-.04 0-.11-.049-.201-.117C7.579 16.5 3.62 12.569 3.62 8.921c0-2.608 1.732-4.344 4.069-4.344 1.893 0 2.98 1.148 3.62
Эти иконки тоже нужно поменять

2023-03-28 20:53 UTC, makcwell commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +                </Grid>
А мы можем сделать проще, внизу блока добавить Text Field из MUI который не нужно вызывать, он всегда активный,  и кнопку на добавление комментария по стилистике я бы предложил - import SendIcon from '@mui/icons-material/Send';
Для красоты можно даже сделать чтобы кнопка рендерилась как только что-то начинаешь вводить в поле Text Field и пропадала если текст удаляешь, тогда не придется следить за выполнением пустого запроса на сервер

В таком случае не понадобятся лишние хуки и react-hook-form.

2023-03-29 11:28 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/Card/myCard.jsx
>  import Chip from '@mui/material/Chip';
Он не лишний. Он был просто импортирован не именованным образом. Сделал через именованный. Согласен, лучше придерживаться одного формата импорта

2023-03-29 11:28 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/Card/myCard.jsx
> +    console.log('props приходит в MyCard >>', card)
Да, согласен, убрал.

2023-03-29 11:28 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/Card/myCard.jsx
>      }
Убрал

2023-03-29 11:28 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/Card/myCard.jsx
> +                                </svg>
Убрал код svg из разметки заменив из mui

2023-03-29 11:29 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +import { useNavigate } from "react-router-dom";
Поправил

2023-03-29 11:29 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +                                            <path clip-rule="evenodd" d="M12 19.343c-.04 0-.11-.049-.201-.117C7.579 16.5 3.62 12.569 3.62 8.921c0-2.608 1.732-4.344 4.069-4.344 1.893 0 2.98 1.148 3.62
убрал длинный svg добавив компонент из mui

2023-03-29 11:29 UTC, aleksei-zhuikov commented on src/Components/MainList/PostList/CardInfo/CardInfo.jsx
> +                </Grid>
Специально использовал react-hook-form чтобы он у нас был в проекте и видно, что мы знаем как с ним работать и создаем контролируемый элемент.

2023-03-29 17:16 UTC, makcwell approved these changes

2023-03-29 17:18 UTC, merged