Terrein
makcwell/React-PostList pull request #19
Opened 2023-03-27 21:10 UTC by Terrein

1. Добавил пагинацию;
2. Добавил поиск в компонент UserMenu;
3. Синхронизация поиска и пагинации (пагинация  серверная );
4. Добавил в Api  метод getPostPagination, для получения серверной пагинации и поиска;

2023-03-27 22:27 UTC, Yunys26 requested changes
Не понятные какие-то мувы в ПР

Очень много лишнего

И некоторые изменения вообще не понятно зачем сделаны

Так таковой логики с пагинацией не видно, так, как номер страницы захаржкожен

2023-03-27 22:27 UTC, Yunys26 commented on src/API/PostsApi.js
> +            "Authorization": `Bearer ${localStorage.getItem("token")}`
Зачем ?

2023-03-27 22:27 UTC, Yunys26 commented on src/API/PostsApi.js
> -const token = localStorage.getItem("token")
Было же норм

2023-03-27 22:27 UTC, Yunys26 commented on src/API/PostsApi.js
> +            "Authorization": `Bearer ${localStorage.getItem("token")}`
В чем логика вызывать каждый раз токен если его можно получить один раз

2023-03-27 22:27 UTC, Yunys26 commented on src/App.js
> +import { getPostPagination } from "./API/PostsApi";
С большой буквы именуются только компоненты

2023-03-27 22:27 UTC, Yunys26 commented on src/App.js
> -import apiPosts from "./API/PostsApi";
Папки не именуются капсом или с заглавной буквы, возможно именуются в другом языке

Если вы какой то архитектурный шаблон используйте то киньте ссылку на него

2023-03-27 22:27 UTC, Yunys26 commented on src/App.js
> +    const [limit] = useState(9)
Зачем состояние, почему просто константу нельзя завести ?

2023-03-27 22:27 UTC, Yunys26 commented on src/App.js
> +    }, [token, isUpdateCards, debounceSearchQuery, page, limit])
Зачем столько зависимостей ?

2023-03-27 22:27 UTC, Yunys26 commented on src/App.js
> +    const handleFirstRender = useCallback(() => {
Не понятно зачем вообще этот метод, если все состояния и так в исходных значениях находятся

2023-03-27 22:27 UTC, Yunys26 commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
Почему тут захардкожено значение ?

2023-03-27 22:27 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
Смысл этого условия, может стоит выше поднять его ?

2023-03-27 22:27 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +                    onChange={(_, num) => {
Что это такое ? Почему первый параметр именуется _
И почему второй это num

Почему передается callback ?

2023-03-27 22:27 UTC, Yunys26 commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
Почему в файле с константами прописаны стили не понятно

2023-03-27 22:27 UTC, Yunys26 commented on src/constants/constants.js
> +    '& .MuiInputBase-input': {
Не уверен что так можно меняться стили mui

2023-03-27 22:37 UTC, Terrein commented on src/API/PostsApi.js
> +            "Authorization": `Bearer ${localStorage.getItem("token")}`
Некорректно приходит переменная в константу, когда токена нет  null и не обновляется.

2023-03-27 22:39 UTC, Terrein commented on src/App.js
> +    }, [token, isUpdateCards, debounceSearchQuery, page, limit])
Зависимости реакт подсказывает и если нет какой то, ворнинги  появляются с просьбой добавить

2023-03-27 22:41 UTC, Terrein commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
потому что при введении в поиск должен стейт скидываться до 1 страницы, что бы если до поиска ты был на пятой страницы после поиска ты был не на пятой  если она вообще есть

2023-03-27 22:42 UTC, Terrein commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
если пользователь не авторизирован то он не видит пагинацию

2023-03-27 22:45 UTC, Terrein commented on src/Components/MainList/Pagination/pagination.jsx
> +                    onChange={(_, num) => {
первый параметр пропускаю потому, что это event , второй параметр number  выбранной страницы он передается в callback для обновления стейта с номером страницы

2023-03-27 22:46 UTC, Terrein commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
чтобы компонент не захламлять.

2023-03-27 22:46 UTC, Terrein commented on src/constants/constants.js
> +    '& .MuiInputBase-input': {
это с доки взято

2023-03-27 22:47 UTC, Terrein commented on src/App.js
> +    const handleFirstRender = useCallback(() => {
при первом рендере прошлые состояния скидывает до начальных

2023-03-27 22:51 UTC, Yunys26 commented on src/App.js
> +    }, [token, isUpdateCards, debounceSearchQuery, page, limit])
Ну он может что угодно подсказывать, нужно понимать как пбаотают в useEffect зависимости, неужели на все эти переменные вам нужно вызвать перерендер?

2023-03-27 22:51 UTC, Yunys26 commented on src/App.js
> +    const handleFirstRender = useCallback(() => {
Какие прошлый состояния, рендер же первый ?

2023-03-27 22:52 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
Ну а в дом что присылается ? Компонент не может возвращать ничего смысл тогда от него ?

2023-03-27 22:53 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +                    onChange={(_, num) => {
Ну так назови его event у всех параметров должно быть логическое наименование

2023-03-27 22:54 UTC, Yunys26 commented on src/App.js
> +    }, [token, isUpdateCards, debounceSearchQuery, page, limit])
Сколько раз вызывается useEffect этом ?

2023-03-27 22:56 UTC, Terrein commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
компонент рендериться если есть токен, если нет, то видит плашку авторизируйтесь. Условным рендерингом разграничиваем права просмотра авторизированых и не авторизированных пользователей

2023-03-27 22:57 UTC, Yunys26 commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
Ну а почему файл называется Constants а тут прописаны стили ?

2023-03-27 22:58 UTC, Terrein commented on src/Components/MainList/Pagination/pagination.jsx
> +                    onChange={(_, num) => {
Если его объявляешь, то не хорошо, что он не используется или нет?  _ за объявление не считается

2023-03-27 22:59 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
В общем условие избыточно в этом компоненте

2023-03-27 23:01 UTC, Terrein commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
тут прописаны  не стили, а компоненты стилизованные styled material ui, могу их отдельно в папку разместить

2023-03-27 23:03 UTC, Yunys26 commented on src/API/PostsApi.js
> +// const onResponse = (res) => {
Закоменченный код удалите

2023-03-27 23:03 UTC, Yunys26 commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
Уверен что он должен срабатывать каждый раз когда вводиться символ ?

2023-03-27 23:03 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
> +                    onChange={(_, num) => {
_ тоже же можно использовать как параметр, так же как и event, просто это не читабельно такое использовать

Так ты не используешь параметр но другой человек который будем смотреть твой код знает что сюда приходит event, а не _

2023-03-27 23:04 UTC, Terrein commented on src/Components/MainList/Pagination/pagination.jsx
> +        <>{token &&
я могу выше поднять в app и написать  `(token&&<ElementPagination />)` так правильнее будет?

2023-03-27 23:06 UTC, Yunys26 commented
И вообще странный прикол у вас именовать константы с _abcs 

То есть с нижнего подчеркивания, так именуют константы на бэке, определение но не на фронте, ну и это не тот язык где используется

Но вы можете рассказать что означает такое наименование начинающееся с _ 

Может тогда я пойму в чем суть и вопросов не будет

2023-03-27 23:07 UTC, Yunys26 commented
Привезены не понятно с чего вдруг вы используйте в коде CSSinJS и moduleCss

2023-03-27 23:09 UTC, Yunys26 commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
Есть понимание для чего нужен файл constants ?

2023-03-27 23:10 UTC, Terrein commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
не уверен, но у меня, но на поиск дебаунс стоит и поэтому избыточные запросы не проходят и выглядит, как корректно отрабатывает могу ошибаться.

2023-03-27 23:12 UTC, Terrein commented on src/constants/constants.js
> +export const Search = styled('div')(({ theme }) => ({
ок вынесу в папку)

2023-03-27 23:15 UTC, Terrein commented on src/API/PostsApi.js
> -const token = localStorage.getItem("token")
при записи не обновляется поэтому надежнее брать из ЛС

2023-03-27 23:16 UTC, Terrein commented on src/App.js
> +    const [limit] = useState(9)
поправлю

2023-03-27 23:16 UTC, Terrein commented on src/App.js
> +    }, [token, isUpdateCards, debounceSearchQuery, page, limit])
по дебагерру вызывается 1 раз)

2023-03-27 23:22 UTC, Terrein commented on src/App.js
> +    const handleFirstRender = useCallback(() => {
без setPage  при выходе и входе обратно  остается открыта страница на которой был до выхода и с результатом поиска, который был до выхода поэтому чищу стейт  setSearchQuery('')  могу это при выходи чистить

2023-03-28 11:26 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +
Каждый файл со стилями должен относиться конкретно к какой то компоненте.

Файл внутри стили только к Search и тд

2023-03-28 11:26 UTC, Yunys26 commented on src/constants/constants.js
> +export const userAgreement = 'Регистрируясь на сайте, вы соглашаетесь с нашими Правилами и Политикой конфиденциальности и соглашаетесь на информационную рассылку.'
В телегу же скинул как неизменяемые константы именуются USER_AGREEMENT

2023-03-28 11:26 UTC, Yunys26 commented on src/constants/constants.js
> +export const limit = 9
LIMIT

2023-03-28 11:26 UTC, Yunys26 commented on src/Components/MainList/Pagination/pagination.jsx
>          </>
Зачем тут React.Fragment ?

2023-03-28 11:26 UTC, Yunys26 commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
Но сама суть что стейт меняется все время на один даже с задержкой, выглядит как то некорректно

2023-03-28 11:26 UTC, Yunys26 commented on src/Components/Header/AuthCompotents/UserMenu/userMenu.jsx
>      const handleLogOut = () => {
Разберитесь как работает useCallback и для чего он нужен при рендере и перерендере

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +                    {(token && <ElementPagination />)}
Огонь, можно объединить с верхнем условием, зачем два раза вызывать одинаковое условие, сделай общее

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +    }, [isUpdateCards])
Зачем мемозиировать значение если оно всегда изменяется?

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +import { limit } from "./constants/constants";
Импорт нормальный нужно сделать

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +    const debounceSearchQuery = useDebounce(searchQuery, 700)
Можно в константу вынести по идее, но это супер доебка :)

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +            })()
Как это называется ?

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +            })()
Уверен что это вообще стоит использовать? 
И где такое использовали ?

2023-03-28 11:26 UTC, Yunys26 commented on src/App.js
> +            page,
Как то по красивее сделай, в переменную вынеси например

2023-03-28 11:26 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +        paddingLeft: `calc(1em + ${theme.spacing(4)})`,
Единицы измерения должны быть едиными, а не где rem, где то em, где то px

2023-03-28 11:26 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +            width: '12ch',
Тоже самое

2023-03-28 12:57 UTC, Terrein commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +        setPage(1)
я  пока не додумался, как оптимальнее сделать

2023-03-28 13:01 UTC, Terrein commented on src/materialStyledComponent/styledComponent.jsx
> +
тут стили  и сами компонетны задаются, я могу на отдельные файлы разбить, но в этом мало смысла или нет?
в доке они вообще в одном компоненте поиска делают https://mui.com/material-ui/react-app-bar/#SearchAppBar.js

2023-03-28 13:12 UTC, Terrein commented on src/App.js
> +import { limit } from "./constants/constants";
тут не совсем понял, нормальный это какой?

2023-03-28 13:13 UTC, Terrein commented on src/App.js
> +            })()
что ты имеешь ввиду вызов анонимной функции в юз эффекте или ты про иф?

2023-03-28 13:14 UTC, Terrein commented on src/App.js
> +            })()
я могу написать просто функцию и вызвать ее, а могу просто анонимную написать и это ее вызов
`(async () => {
                const answer = await getPostPagination(page, LIMIT, debounceSearchQuery)
                setPageQty(parseInt(Math.ceil(answer?.total / LIMIT)))
                setCards(answer?.posts)
                if (answer?.postLength === 0) {
                    setPage(1)
                }
            })()`

2023-03-28 13:15 UTC, Terrein commented on src/materialStyledComponent/styledComponent.jsx
> +        paddingLeft: `calc(1em + ${theme.spacing(4)})`,
это из доки

2023-03-28 13:16 UTC, Terrein commented on src/materialStyledComponent/styledComponent.jsx
> +            width: '12ch',
и это

2023-03-28 13:17 UTC, Terrein commented on src/App.js
> +            page,
вынести значение контекста в переменную и в контексте  вызывать ее? мне кажется это не очень понятно будет

2023-03-28 21:12 UTC, Yunys26 approved these changes

2023-03-28 21:12 UTC, Yunys26 commented on src/Components/Header/AuthCompotents/UserMenu/search.jsx
> +    return (<>
Зачем тут fragment?

2023-03-28 21:12 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +
Дока там просто пример они же не будут доку делить на файлы

2023-03-28 21:12 UTC, Yunys26 commented on src/App.js
> +import { limit } from "./constants/constants";
./constants

2023-03-28 21:12 UTC, Yunys26 commented on src/App.js
> +            })()
Ну а смысл, так уже никто не пишет и это не читабельно, бэд практис ты же не на var пишешь, есть более свежий аналог этой записи

2023-03-28 21:12 UTC, Yunys26 commented on src/App.js
> +            })()
В доке что написано ? На счет useEffect ?

Там ответ на твой вопрос по сути

Короче самовызывающиеся выражения оставь для старого синтаксиса

2023-03-28 21:12 UTC, Yunys26 commented on src/App.js
> +            page,
Но у тебя просто такая портянка в jsx

2023-03-28 21:12 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +        paddingLeft: `calc(1em + ${theme.spacing(4)})`,
Но проект то у вас не из доки а вы его сами пишите

2023-03-28 21:12 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +            width: '12ch',
Вы хотя бы посмотрите, для чего нужны и зачем эти величины и сколько одна единица этой величины соответствует px

2023-03-28 21:12 UTC, Yunys26 commented on src/materialStyledComponent/styledComponent.jsx
> +            width: '12ch',
Короче используйте что то одно, так не правильно делать

2023-03-29 07:50 UTC, merged